name: ESLint
on:
  push:
    branches:
      - master
      - indev
      - 'side/**'
      - 'feature/**'
    paths-ignore:
      # We ignore node modules, the build that TypeScript creates and the root directory
      # because it's mostly modifying the source code, not really these folder/files
      - 'node_modules/**'
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'
      - 'renovate.json'
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 13.x, 14.x]
    steps:
      - name: Setup repository in local
        uses: actions/checkout@v1
      - name: Use Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Installs global dependencies
        run: npm i -g eslint postcss-cli concurrently react-scripts
      - name: Installs local dependencies
        run: npm i
      - name: Installs local dependencies
        run: npm i --package-json-only && npm audit fix && npm i
        if: ${{ failure() }}
      - name: Lints the repository
        run: eslint src --ext .ts,.tsx --fix --ignore-path .gitignore
      - name: Runs End to End testing
        run: postcss src/styles/**/*.scss --dir src/styles/ --ext css --verbose && rm -fr src/styles/**/*.css.map && ./node_modules/.bin/cypress run